[directory]
truncate_to_repo = true
truncation_length = 10

[character]
symbol = "異 "

[package]
disabled = true
symbol = " "

[python]
symbol = " "

[nodejs]
symbol = " "

[hg_branch]
symbol = " "

[git_branch]
symbol = " "

[conda]
symbol = " "

[java]
symbol = " "

[docker]
symbol = " "
